emotionChooses:
  - 困惑: 很抱歉让你感到困惑，这道题确实比较难！---很抱歉让你感到困惑，继续加油，不要放弃哦！---emotion.gif
  - 无聊: 很抱歉让你感到无聊，下面试试更有挑战性的题目吧！---很抱歉让你感到无聊，要集中注意力哦！---emotion.gif
  - 沮丧: 很抱歉让你感到沮丧，继续加油，你可以的！---很抱歉让你感觉沮丧，这道题确实有点难，接下来试试简单一点的题目。---emotion.gif
  - 愉快: 我很高兴你感到愉快，真为你感到开心！---我很高兴你感到愉快，不要紧张吶！---emotion.gif

questions:
  -
    body: 1. 水是宝贵的自然资源，下列说法正确的是（）
    choose: ["A.水在自然界中不断循环，取之不尽，用之不竭。", "B.水是常见的溶剂，广泛用于工农业生产", "C.为了节约用水，可以用工业废水直接浇灌农田。", "D.自来水中只含有水分子，不含其他粒子。"]
    rightChoose: 1
    explain: 详细解释：正确答案为B。水可以溶解许多物质，是最常用的溶剂，广泛用于工农业生产。
    kind: 练习

  - body: 2. 我省环保部门按新修订的《环境空气质量标准》，着力做好细颗粒物和臭氧等新增指标的检测，下列说法正确的是（）
    choose: ["A.燃烧植物秸秆不会造成大气污染", "B.吸入细颗粒物对人体健康没有危害", "C.化学在环境检测和保护中起重要作用", "D.臭氧是一种氧化物"]
    rightChoose: 2
    explain: 详细解释：正确答案是C。可以利用化学检测环境中的污染情况并能解决污染状况。
    kind: 练习

  - body: 1. 在一个学习实验中，请3名被试分别完成相同的10道题。3名被试花费的时间依次为0.8小时，1.0小时，1.2小时，则这3名被试平均完成这10道题的速度为（ ）（题/小时）
    choose: ["A. 0.1", "B. 1", "C. 5", "D.10"]
    rightChoose: 3
    explain: que1.png
    kind: 学习

  - body: 2. 在一组数据中，P10=35，P25=52，P50=63，P75=74，P90=85，该组数据的四分位差是（ ）
    choose: ["A.25", "B.22", "C.11", "D.50"]
    rightChoose: 2
    explain: que2.png
    kind: 学习

  - body: 3. 某智力测验的智商分数转化公式是IQ=100+15Z，测验分数符合标准正态分布，则智商145以上的人占参加测验人员的比例是（ ）%（Z=1时，p=0.34；Z=2时，p=0.477；Z=3时，p=0.4987）
    choose: ["A.0.13", "B.0.26", "C.2.46", "D.5.56"]
    rightChoose: 0
    explain: que3.png
    kind: 学习

  - body: 4. 一组实验分数近似正态分布，其平均分为65.5，标准差为5分，问分数在55.5分和75.5分之间的人数占全体人数的百分比是（ ）%
    choose: ["A.68.2", "B.92.5", "C.95.4", "D.99.6"]
    rightChoose: 2
    explain: que4.png
    kind: 学习

  - body: 5. 总体的均值为100，标准差为20，从总体中抽取一个容量为25的样本，则样本均值的标准差为（ ）
    choose: ["A.4", "B.5", "C.20", "D.30"]
    rightChoose: 0
    explain: que5.png
    kind: 学习

  - body: 6. 某研究选取容量均为5的三个独立样本，进行方差分析，其总自由度为（ ）
    choose: ["A.15", "B.12", "C.2", "D.14"]
    rightChoose: 3
    explain: que6.png
    kind: 学习

  - body: 7. 在一个组间的单因素方差分析中，已知F(2，24)=0.90，则研究样本的容量为（ ）
    choose: ["A.25", "B.26", "C.27", "D.28"]
    rightChoose: 2
    explain: que7.png
    kind: 学习

  - body: 8. 3×2的两因素组间方差分析中，交互效应的自由度为（  ）
    choose: ["A.2", "B.6", "C.5", "D.4"]
    rightChoose: 0
    explain: que8.png
    kind: 学习

  - body: 9. 在一个2×2×2的实验设计中，存在的交互作用有（  ）个
    choose: ["A.3", "B.4", "C.6", "D.8"]
    rightChoose: 1
    explain: que9.png
    kind: 学习

  - body: 10. 一套单项选择题有48道题目，每题有4个选项。如果要从统计上（95%的把握）排除猜测作答的情形，考生正确回答的题目数量至少应该是（  ）道（α=0.05，Zα=1.64）
    choose: ["A.16", "B.17", "C.18", "D.19"]
    rightChoose: 1
    explain: que10.png
    kind: 学习

  - body: 1. 在英语词汇记忆实验中，要求4名被试分别记忆相同的10个生词。这4名被试花费的时间依次为5min，6min，8min，10min，则这4名被试平均记忆这10个生词的速度为（    ）（个/min）
    choose: ["A. 0.4", "B. 0.5", "C. 2.5", "D. 7.3"]
    rightChoose: 3
    kind: 后测

  - body: 2. 在一组数据中，P10=24，P25=42，P50=68，P75=82，P90=94，该组数据的四分位差是（    ）
    choose: ["A. 20", "B. 35", "C. 40", "D. 70"]
    rightChoose: 0
    kind: 后测

  - body: 3. 某测验分数的转化公式是X=70+4Z，测验分数符合标准正态分布，则分数在78分以上的人占参加测验人员的比例是（    ）%（Z=1时，p=0.34；Z=2时，p=0.477；Z=3时，p=0.4987）
    choose: ["A.0.13", "B.2.3", "C.16", "D.97.7"]
    rightChoose: 1
    kind: 后测

  - body: 4. 一组实验分数近似正态分布，其平均分为45，标准差为5分，问分数在40分和50分之间的人数占全体人数的百分比是（    ）%（Z=1时，p=0.34；Z=2时，p=0.477；Z=3时，p=0.4987）
    choose: ["A.68", "B.92.5", "C.95.4", "D.99.6"]
    rightChoose: 0
    kind: 后测

  - body: 5. 总体的均值为80，标准差为12，从总体中抽取一个容量为16的样本，则样本均值的标准差为（    ）
    choose: ["A.3", "B.4", "C.5", "D.6"]
    rightChoose: 0
    kind: 后测

  - body: 6. 在一个单因素组间设计的方差分析中，研究者报告的总自由度为32，则此研究的被试量为（    ）
    choose: ["A.32", "B.33", "C.34", "D.35"]
    rightChoose: 1
    kind: 后测

  - body: 7. 在一个组间的单因素方差分析中，已知F(3，28)=0.90，则研究样本的容量为（    ）
    choose: ["A. 30", "B. 31", "C. 32", "D. 33"]
    rightChoose: 2
    kind: 后测

  - body: 8. 3×3的两因素组间方差分析中，交互效应的自由度为（    ）
    choose: ["A.3", "B.4", "C.8", "D.9"]
    rightChoose: 1
    kind: 后测

  - body: 9. 在一个2×2×3的实验设计中，存在的交互作用有（    ）个
    choose: ["A.3", "B.4", "C.6", "D.12"]
    rightChoose: 1
    kind: 后测

  - body: 10. 某学业成就测验由100道正误题组成，每题1分。如果要从统计上（99%的把握）排除猜测作答的情形，考生正确回答的题目数量至少应该是（    ）道（α=0.01，Zα=2.33）
    choose: ["A.59", "B.60", "C.62", "D.63"]
    rightChoose: 2
    kind: 后测

surveys:
  -
    kind: FIVE
    name: 情绪量表
    intro: 请根据你此时此刻的情绪状态，选择符合你的选项。
    questions:
      - body: 1. 活跃的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 2.充满热情的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 3.快乐的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 4.兴高采烈的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 5.兴奋的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 6.自豪的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 7.欣喜的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 8.精神充沛的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 9.感激的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 10.羞愧的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 11.难过的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 12.害怕的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 13.紧张的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 14.惊恐的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 15.内疚的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 16.易怒的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 17.战战兢兢的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
      - body: 18.恼怒的
        choose: ["完全不符合", "比较不符合", "不确定", "比较符合","完全符合"]
  -
    kind: FIVE
    name: 代理感知量表
    intro: 以下是关于在学习过程中屏幕左下方的教学代理的评价，请根据自己的实际情况，选择符合你的选项。
    questions:
      - body: 1.	系统中的代理理解我的情绪并提供了支持。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 2.	代理使我对学习内容有了更深入的思考。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 3.	代理使教学内容变得有趣。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 4.	代理使我反思我正在学习的内容。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 5.	代理一直吸引着我的注意力。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 6.	代理有效地展示了学习材料。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 7.	代理帮助我专注于学习内容。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 8.	代理使我专注于相关信息。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 9.	代理提高了我对学习内容的了解。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 10.	代理是有趣的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 11.	代理是愉快的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 12.	代理是知识渊博的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 13.	代理是智能的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 14.	代理是有用的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 15.	代理是有帮助的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 16.	代理与教师相似。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 17.	代理是有个性的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 18.	代理的情绪很自然。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 19.	代理与人类相似。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 20.	代理的动作很自然。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 21.	代理表达了情绪。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 22.	代理是有表现力的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 23.	代理是热情的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 24.	代理是令人愉快的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 25.	代理是激励人心的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
      - body: 26.	代理是友好的。
        choose: ["非常不赞同", "比较不赞同", "不确定", "比较赞同","完全赞同"]
  -
    kind: FIVE
    name: 动机量表
    intro: 针对刚才的学习，请仔细阅读每一项，根据自己的实际情况，选择符合你的选项。
    questions:
      - body: 1.我觉得刚才的学习很容易。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 2.我非常喜欢通过这个系统来学习。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 3.在我阅读了这个学习系统的介绍后，我很清楚自己将要学习什么。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 4.完成刚才的学习任务让我很有成就感。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 5.通过刚才的学习，我有信心在后面学习中取得好成绩。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 6.能够成功地完成这次学习任务让我感觉不错。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 7.通过刚才的学习，我有信心能掌握所学内容。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 8.我喜欢这个学习系统中的内容，我想知道更多与这些内容有关的知识。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 9.这个学习系统中的内容很好，让我有信心学好这个材料。
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 10.系统中给予的解释或反馈语言让我感到这是对自己努力的奖励
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
      - body: 11.这个系统设计得很好，我很乐意使用它
        choose: ["极不符合", "不符合", "不确定", "符合","完全符合"]
  -
    kind: NINE
    name: 对学习内容的认知负荷评价
    intro: 请针对刚才的学习内容，从以下9个数字中选择你认为合适的数字：
    questions:
      - body: 1.你认为刚才的学习内容难度如何？
        choose: ["非常简单", "2", "3", "4","5", "6", "7", "8", "非常困难"]
      - body: 2.在刚才的学习过程中，你投入了多少努力？
        choose: ["最少努力", "2", "3", "4","5", "6", "7", "8", "最大努力"]
      - body: 3.你认为利用这个学习系统学习起来是否方便？
        choose: ["非常方便", "2", "3", "4","5", "6", "7", "8", "非常困难"]